version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/vrsdb
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vrsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  unity-editor:
    image: placeholder/unity
    labels:
      - "tool=Unity"
      - "version=2021.3"
      - "note=Used for VR scene creation (not containerized)"
    deploy:
      replicas: 0

  blender:
    image: placeholder/blender
    labels:
      - "tool=Blender"
      - "note=Used for 3D modeling assets (not containerized)"
    deploy:
      replicas: 0

  maya:
    image: placeholder/maya
    labels:
      - "tool=Autodesk Maya"
      - "note=Used for animation and rigging (not containerized)"
    deploy:
      replicas: 0

volumes:
  pgdata:
